# ---------- 定时任务相关 ----------
news_push_time: 0 0/5 * * * ? 
signin_time: 0 0 4 * * ?
sanity_push_time: 0 */7 * * * ?

# ---------- 通用配置 ----------
# 是否使用公共cookie
use_public_cookie: true
# 是否允许用户导入抽卡记录
allow_import: false

# ---------- 面板图相关 ----------
# 是否允许普通用户上传面板图
allowImgUpload: false
# 是否允许普通用户获取原图
allowGetOrigin: false
# 是否允许普通用户获取面板图列表
allowGetList: false
# 是否允许普通用户删除面板图
allowImgDelete: false

# ---------- 定时任务列表 ----------
# 自动签到列表
waves_auto_signin_list: []
# 体力推送列表
waves_auto_push_list: []
# 公告推送列表
waves_auto_news_list: []